apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribe-manager
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscribe-manager
  template:
    metadata:
      labels:
        app: subscribe-manager
    spec:
      containers:
      - name: subscribe-manager
        image: uhub.service.ucloud.cn/entropypool/subscribe-manager:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: subscribe-manager
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 50300
    targetPort: 50300
  - name: grpc
    port: 50301
    targetPort: 50301
  - name: prometheus
    port: 50302
    targetPort: 50302
  selector:
    app: subscribe-manager
